apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prefect-server-
resources:
  - ../../base
patchesStrategicMerge:
  - patch-sts.yaml
configMapGenerator:
  - name: postgresql-initdb
    files:
      - initdb.sql
