apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server-agent
  labels:
    app: prefect-server-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server-agent
  template:
    metadata:
      labels:
        app: prefect-server-agent
    spec:
      serviceAccountName: default
      containers:
        - name: agent
          image: docker.io/prefecthq/prefect:core-0.15.13
          imagePullPolicy: Always
          command:
            - bash
            - -c
          args:
            - prefect agent kubernetes start
          env:
            - name: PREFECT__CLOUD__API
              value: http://prefect-server-apollo:4200/graphql
            - name: NAMESPACE
              value: default
            - name: IMAGE_PULL_SECRETS
              value: ""
            - name: PREFECT__CLOUD__AGENT__LABELS
              value: "[]"
            - name: JOB_MEM_REQUEST
              value: ""
            - name: JOB_MEM_LIMIT
              value: ""
            - name: JOB_CPU_REQUEST
              value: ""
            - name: JOB_CPU_LIMIT
              value: ""
            - name: IMAGE_PULL_POLICY
              value: ""
            - name: SERVICE_ACCOUNT_NAME
              value: default
            - name: PREFECT__BACKEND
              value: server
            - name: PREFECT__CLOUD__AGENT__AGENT_ADDRESS
              value: http://0.0.0.0:8080
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
