apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server-graphql
  labels:
    app: prefect-server-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server-graphql
  template:
    metadata:
      labels:
        app: prefect-server-graphql
    spec:
      serviceAccountName: default
      initContainers:
        - name: database-upgrade
          image: docker.io/prefecthq/server:core-0.15.13
          command:
            - prefect-server
          args:
            - database
            - upgrade
            - --yes
          env:
            - name: PREFECT_SERVER__API__URL
              value: http://prefect-server-hasura:3000/v1alpha1/graphql
            - name: PREFECT_SERVER__DATABASE__HOST
              value: prefect-server-postgresql
            - name: PREFECT_SERVER__DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: username
            - name: PREFECT_SERVER__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: password
            - name: PREFECT_SERVER__HASURA__HOST
              value: prefect-server-hasura
            - name: PREFECT_SERVER__HASURA__PORT
              value: "3000"
            - name: PREFECT_SERVER__SERVICES__APOLLO__PORT
              value: "4200"
            - name: PREFECT_SERVER__SERVICES__GRAPHQL__PORT
              value: "4201"
      containers:
        - name: graphql
          image: "prefecthq/server:core-0.15.13"
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - "python src/prefect_server/services/graphql/server.py"
          env:
            - name: PREFECT_SERVER_DB_CMD
              value: "echo 'DATABASE MIGRATIONS SKIPPED'"
            - name: PREFECT_SERVER__API__URL
              value: http://prefect-server-hasura:3000/v1alpha1/graphql
            - name: PREFECT_SERVER__DATABASE__HOST
              value: prefect-server-postgresql
            - name: PREFECT_SERVER__DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: username
            - name: PREFECT_SERVER__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: password
            - name: PREFECT_SERVER__HASURA__HOST
              value: prefect-server-hasura
            - name: PREFECT_SERVER__HASURA__PORT
              value: "3000"
            - name: PREFECT_SERVER__SERVICES__APOLLO__PORT
              value: "4200"
            - name: PREFECT_SERVER__SERVICES__GRAPHQL__PORT
              value: "4201"
          ports:
            - name: web
              containerPort: 4201
          livenessProbe:
            httpGet:
              path: /health
              port: web
          readinessProbe:
            httpGet:
              path: /health
              port: web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
