apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server-apollo
  labels:
    app: prefect-server-apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server-apollo
  template:
    metadata:
      labels:
        app: prefect-server-apollo
    spec:
      containers:
        - name: apollo
          image: docker.io/prefecthq/apollo:core-0.15.13
          command:
            - bash
            - -c
          args:
            - /apollo/post-start.sh && npm run serve
          env:
            - name: HASURA_API_URL
              value: http://prefect-server-hasura:3000/v1alpha1/graphql
            - name: PREFECT_API_URL
              value: http://prefect-server-graphql:4201/graphql/
            - name: PREFECT_API_HEALTH_URL
              value: http://prefect-server-graphql:4201/health
            - name: GRAPHQL_SERVICE_HOST
              value: "http://prefect-server-graphql"
            - name: GRAPHQL_SERVICE_PORT
              value: "4201"
            - name: PREFECT_SERVER__API__URL
              value: http://prefect-server-hasura:3000/v1alpha1/graphql
            - name: PREFECT_SERVER__DATABASE__HOST
              value: prefect-server-postgresql
            - name: PREFECT_SERVER__DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: username
            - name: PREFECT_SERVER__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prefect-server-postgresql
                  key: password
            - name: PREFECT_SERVER__HASURA__HOST
              value: prefect-server-hasura
            - name: PREFECT_SERVER__HASURA__PORT
              value: "3000"
            - name: PREFECT_SERVER__SERVICES__APOLLO__PORT
              value: "4200"
            - name: PREFECT_SERVER__SERVICES__GRAPHQL__PORT
              value: "4201"
          ports:
            - name: web
              containerPort: 4200
          livenessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: web
          readinessProbe:
            httpGet:
              path: /.well-known/apollo/server-health
              port: web
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
